In [1]:
# this is the code for 8 queen Dynamic programming problem.

In [129]:
# importing all the required libraries
import numpy as np

In [130]:
# board state memory
board_state_memory:dict = {}

In [131]:
N = 8

# creating an N * N board
board = np.zeros((N, N), np.int8)

In [132]:
board

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [133]:
# create board string
def create_board_string(board):
    board_string = ''
    for i in range(N):
        for j in range(N):
            board_string += str(board[i][j])
    return board_string

In [134]:
# testing the Create_board_string function
create_board_string(board)

'0000000000000000000000000000000000000000000000000000000000000000'

In [135]:
# copying the board and positioning the queen at 1 column, 1 row
board_copy = board.copy()
board_copy[0, 1] = 1

In [136]:
board_copy
create_board_string(board_copy)

'0100000000000000000000000000000000000000000000000000000000000000'

In [137]:
def is_board_safe(board):
    
    #This is where the dynaic programming comes into picture. Where we use the board_state_memory to cache.
    board_key = create_board_string(board)
    
    if board_key in board_state_memory:
        print('Using Cached Information')
        return board_state_memory[board_key]
    
    # calculate the sum in every row of the board
    row_sum = np.sum(board, axis = 1)
    # checking if a row has more than 1 queen - we will check the sum or elements in a row
    if len(row_sum[np.where(row_sum > 1)]) > 0:
        board_state_memory[board_key] = False
        return False
    
    # checking column sum in every row of the board
    col_sum = np.sum(board, axis = 0)
    if len(col_sum[np.where(col_sum > 1)]) > 0:
        board_state_memory[board_key] = False
        return False
    
    diags = [board[::-1,:].diagonal(i) for i in range(-board.shape[0] + 1, board.shape[1])]
    
    diags.extend(board.diagonal(i) for i in range(board.shape[1] - 1, -board.shape[0], -1))
    
    for diag in diags:
        if np.sum(diag) > 1:
            board_state_memory[board_key] = False
            return False
        
    board_state_memory[board_key] = True
    return True

In [138]:
board_copy = board.copy()
board_copy[1][0] = 1
board_copy[2][3] = 1
board_copy[0][1] = 1

In [139]:
print(board_copy)
is_board_safe(board_copy)

[[0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


False

In [140]:
# defining the placing of the Queen 

def place_queen_safely(board, column):
    
    if column >= N:
        # All N queens are placed correctly
        return True
    
    for row in range(N):
        board[row][column] = 1
        
        safe = False
        
        if is_board_safe(board):
            safe = place_queen_safely(board, column + 1)
    
        if not safe:
            board[row][column] = 0
            
        else: 
            break
    return safe
    

In [141]:
board_state_memory

{'0100000010000000000100000000000000000000000000000000000000000000': False}

In [142]:
board = np.zeros((N,N), np.int8)
placed = place_queen_safely(board, 0)
print(board)

[[1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]]


In [143]:
placed
# just checking if everything is set.

True


Q-learning and SARSA in Reinforcement Learning.
Q-learning gives us the optimal policy to maximize the returns in a Reinforcement learning.

Agent observes the environment and takes actions based on a policy.
The output of reinforcement learning is a set of actions which maximize the cumulative rewards.

Policy Search algorithms
1. Brute Force methods
2. Policy Gradient methods
3. Value Function metods

Value Function methods are most common

Q-learning techniques (Temporal difference)
SARSA method (Another implementation of Q-learning)